export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART'
export const MODIFY_PRODUCT_QUANTITY = 'MODIFY_PRODUCT_QUANTITY'
export const CALCULATE_FINAL_PRICE = 'CALCULATE_FINAL_PRICE'
export const SUBSTRACT_PRODUCT_QUANTITY = 'SUBSTRACT_PRODUCT_QUANTITY'
export const RESET_CART = 'RESET_CART'

